version: '3'

volumes:
    postgres_data: {}

services:
    postgres:
        image: postgres:12
        environment:
            - POSTGRES_DB=cloud
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
    django:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - postgres
    mailhog:
        image: mailhog/mailhog
        ports:
            - 8025:8025
    
