version: "3"

services:
  django:
    image: cloud
    ports:
      - "8000:8000"
    env_file: ./.env
    depends_on: 
      - redis

  nginx:
    image: nginx
    ports:
      - "80:80"

  redis:
    image: redis:alpine

  celery:
    image: cloud
    command: celery -A cloud worker --loglevel=INFO
    env_file: ./.env
    depends_on: 
      - django
      - redis