version: "3"

services:
  django:
    image: cloud
    ports:
      - "8000:8000"
    env_file: ./.env
    depends_on: 
      - redis
  nginx:
    image: nginx
    ports:
      - "80:80"
    env_file: ./.env
  redis:
    image: redis:alpine
    env_file: ./.env
  celery:
    image: cloud
    command: celery -A cloud worker --loglevel=INFO
    env_file: ./.env
    volumes:
      - ./:/usr/src/app
    depends_on: 
      - django