# Generated by Django 3.2.5 on 2021-07-13 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='topics', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'topic',
                'verbose_name_plural': 'topics',
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=254, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.FloatField(verbose_name='price')),
                ('discount_price', models.FloatField(blank=True, null=True, verbose_name='discount price')),
                ('image', models.ImageField(upload_to='workshops', verbose_name='image')),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(verbose_name='start date')),
                ('hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weeks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('schedule', models.TextField(blank=True, null=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'beginner'), (2, 'intermediate'), (3, 'advanced')], default=1, verbose_name='level')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('private', models.BooleanField(default=False, verbose_name='private')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.topic', verbose_name='topic')),
            ],
            options={
                'verbose_name': 'workshop',
                'verbose_name_plural': 'workshops',
            },
        ),
    ]
