# Generated by Django 3.2.5 on 2021-07-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='max_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='min_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
